# Generated by Django 3.2.2 on 2021-05-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impactfee', '0002_auto_20210527_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceareacalculator',
            name='use_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impactfee.usetype'),
        ),
        migrations.AlterField(
            model_name='serviceareacalculator',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impactfee.servicearea'),
        ),
        migrations.CreateModel(
            name='UseSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('usesubtypename', models.CharField(max_length=100)),
                ('parksandrecfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('police', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('streets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('usetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impactfee.usetype')),
            ],
        ),
        migrations.AddField(
            model_name='serviceareacalculator',
            name='use_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impactfee.usesubtype'),
        ),
    ]
