# Generated by Django 3.2.2 on 2021-06-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impactfee', '0003_auto_20210528_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usesubtype',
            old_name='usesubtypename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usetype',
            old_name='usetypename',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='servicearea',
            table=None,
        ),
    ]
