# Generated by Django 3.1.2 on 2021-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactfee', '0004_auto_20210623_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceareacalculator',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceareacalculator',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceareacalculator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
