# Generated by Django 3.2.2 on 2021-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactfee', '0005_auto_20210627_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('minsize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxsize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parksandrecfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('police', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('streets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalfee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='serviceareacalculator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
